# frozen_string_literal: true

require "csv"

module GithubIssueSync
  # Represents one GitHub issue as a flat hash keyed by CSV column name.
  # Knows how to build itself from a Sawyer::Resource (GitHub API response)
  # or from a CSV row hash, and how to emit its values as an ordered array
  # suitable for CSV serialisation.
  class IssueRow
    COLUMNS = [
      "GitHub Issue #",
      "State",
      "Title",
      "Type",
      "Priority",
      "Section",
      "Element / Feature",
      "Description",
      "Labels",
      "URL"
    ].freeze

    # Type labels recognised by import-qa-issues (lowercase match).
    TYPE_LABELS = %w[bug enhancement ux copy question security performance].freeze

    # Priority labels → human-readable names.
    PRIORITY_LABEL_MAP = {
      "critical"     => "Critical",
      "high-priority" => "High",
      "pre-launch"   => "High",   # legacy: pre-launch treated as High priority
      "low-priority"  => "Low"
    }.freeze

    # Emoji prefixes written by import-qa-issues build_body_v2.
    PRIORITY_EMOJI_RE = /\A(?:🔴|🟠|🟡|🟢)\s*/

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    # Build an IssueRow from a Sawyer::Resource returned by Octokit.
    def self.from_github(issue)
      label_names = Array(issue.labels).map(&:name)
      body = issue.body.to_s

      new(
        "GitHub Issue #" => issue.number.to_s,
        "State" => issue.state.to_s,
        "Title" => issue.title.to_s,
        "Type" => extract_type(body, label_names),
        "Priority" => extract_priority(body, label_names),
        "Section" => extract_table_field(body, "Page / Section"),
        "Element / Feature" => extract_table_field(body, "Element / Feature"),
        "Description" => body,
        "Labels" => label_names.join(", "),
        "URL" => issue.html_url.to_s
      )
    end

    # Build an IssueRow from a CSV::Row or plain Hash keyed by column name.
    def self.from_csv_row(row)
      data = COLUMNS.each_with_object({}) do |col, h|
        h[col] = row[col].to_s
      end
      new(data)
    end

    # ------------------------------------------------------------------
    # Instance interface
    # ------------------------------------------------------------------

    def initialize(data)
      @data = data
    end

    def [](key) = @data[key]
    def values = COLUMNS.map { |c| @data[c] }
    def to_h = @data.dup
    def keys = @data.keys

    # ------------------------------------------------------------------
    private

    # ------------------------------------------------------------------

    # Parse a field value out of the markdown table generated by import-qa-issues.
    # Looks for:   | **Field Name** | Value |
    def self.extract_table_field(body, field_name)
      pattern = /\|\s*\*\*#{Regexp.escape(field_name)}\*\*\s*\|\s*(.+?)\s*\|/
      body.match(pattern)&.captures&.first.to_s.strip
    end
    private_class_method :extract_table_field

    # Try the structured body table first; fall back to scanning label names.
    def self.extract_type(body, label_names)
      from_table = extract_table_field(body, "Type")
      return from_table unless from_table.empty?

      matched = label_names.find { |l| TYPE_LABELS.include?(l.downcase) }
      matched ? matched.capitalize : ""
    end
    private_class_method :extract_type

    # Try the structured body table (strip emoji prefix); fall back to labels.
    def self.extract_priority(body, label_names)
      from_table = extract_table_field(body, "Priority")
      unless from_table.empty?
        # Strip emoji and anything after the em-dash: "🟠 High — pre-launch preferred" → "High"
        cleaned = from_table.sub(PRIORITY_EMOJI_RE, "").split(/\s*[—-]/).first.to_s.strip
        return cleaned unless cleaned.empty?
      end

      label_names.each do |l|
        mapped = PRIORITY_LABEL_MAP[l.downcase]
        return mapped if mapped
      end
      ""
    end
    private_class_method :extract_priority
  end
end
